name: diggg
version: 1 

libraries:
- name: "django"
  version: "1.4"
- name: "simplejson" 
  version: "3.3.1"
- name: "feedparser"
  version: "5.1.3"

handlers:
- url: /static/
  static_path: static




